# Use postgres/example user/password credentials
version: "3.1"

services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

  app:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
    command: sh -c 'npm i && npm run deploy:docker'
    restart: on-failure
    depends_on:
      - postgresdb
      - adminer
      - redis
